name: injector
description: Simple dependency injection for dart

version: 1.0.1
homepage: https://www.tikkr.app
author: info@tikkr.app

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  meta: "^1.1.5"

dev_dependencies:
  test: "1.3.0"