name: injector
description: Simple dependency injection for dart

version: 0.0.1
homepage: https://www.tikkr.app
author: info@tikkr.app

environment:
  sdk: '>=2.0.0-dev.52.0 <2.0.0'

dev_dependencies:
  test: ^0.12.30