name: injector
description: injector is a simple to use and lightweight dependency injection library for dart
version: 1.0.10-nullsafety.0
homepage: https://github.com/tappeddev/injector

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dependencies:
  meta: 1.3.0-nullsafety.2

dev_dependencies:
  test: 1.16.0-nullsafety.2
  extra_pedantic: 1.2.0