name: injector
description: injector is a simple to use and lightweight dependency injection library for dart

version: 1.0.8
homepage: https://github.com/tappeddev/injector
author: Tapped <contact@tapped.dev>

environment:
  sdk: '>=2.7.2 <3.0.0'

dependencies:
  meta: ^1.1.8

dev_dependencies:
  test: ^1.15.1
  extra_pedantic: 1.2.0